// frontend/react-demo/src/components/TaskList/TaskList.tsx
import { useMemo } from "react";
import { ITask } from "../../models";

export interface TaskListProps {
  tasks: ITask[];
}

export const TaskList: React.FC<TaskListProps> = ({ tasks }) => {
  const [pending, done] = useMemo(() => {
    return tasks.reduce(
      (arr, task) => {
        if (!task.done) arr[0].push(task);
        else arr[1].push(task);
        return arr;
      },
      [[], []] as [ITask[], ITask[]]
    );
  }, [tasks]);
  return (
    <>
      <h3 className="subtitle is-3 mb-1">Pendientes</h3>
      <div className="mb-4">
        {pending.map((task) => (
          <p key={task.id}>{task.text}</p>
        ))}
        {pending.length === 0 && <p>No tienes tareas pendientes.</p>}
      </div>
      <h3 className="subtitle is-3 mb-1">Finalizadas</h3>
      <div className="mb-4">
        {done.map((task) => (
          <p key={task.id}>{task.text}</p>
        ))}
        {done.length === 0 && <p>No tienes tareas finalizadas.</p>}
      </div>
    </>
  );
};

// frontend/angular-demo/src/app/task-list/task-list.component.ts
import {
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import { ITask } from 'src/models/task';

@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.scss'],
})
export class TaskListComponent implements OnInit, OnChanges {
  @Input('task-list') taskList: ITask[] = [];
  pendingTasks: ITask[] = [];
  doneTasks: ITask[] = [];

  constructor() {}

  ngOnChanges(changes: SimpleChanges): void {
    if (!changes.taskList) return;
    const tasks: ITask[] = changes.taskList.currentValue;
    const [pending, done] = tasks.reduce(
      (arr, task) => {
        if (!task.done) arr[0].push(task);
        else arr[1].push(task);
        return arr;
      },
      [[], []] as [ITask[], ITask[]]
    );
    this.pendingTasks = pending;
    this.doneTasks = done;
  }

  ngOnInit(): void {}
}

<h2 class="mat-h2">Pendientes</h2>
<mat-list>
	<div *ngFor="let task of pendingTasks">
		<app-task-item [task]="task"></app-task-item>
	</div>
</mat-list>
<h2 class="mat-h2">Finalizadas</h2>
<mat-list>
	<div *ngFor="let task of doneTasks">
		<app-task-item [task]="task"></app-task-item>
	</div>
</mat-list>
